### ISSUE TITLE
picture

### ISSUE THREAD

**Issue by h4ck3rm1k3** [chihming/awesome-network-embedding#11]
![screenshot from 2018-04-09 06-26-18](https://user-images.githubusercontent.com/34903/38493106-fb660758-3bbe-11e8-94ee-a44a14bab2b8.png)
This how the page looks. The image is truncated.

**Comment by chihming** [comment]
it's the image cache problem
any idea to solve this?

**Comment by h4ck3rm1k3** [comment]
host the image as part of the repo and have it delivered together from the same server.
https://github.com/chihming/awesome-network-embedding/pull/12
