### ISSUE TITLE
Suggested addititions

### ISSUE THREAD

**Issue by ip01** [chihming/awesome-network-embedding#18]
Hi,
I'd suggest to add following items:

1. succinct Pyton3 implementation of node2vec : https://github.com/eliorc/node2vec
2. Attention-based Graph Neural Network for semi-supervised learning https://github.com/dawnranger/pytorch-AGNN
3. Representation Tradeoffs for Hyperbolic Embeddings https://github.com/HazyResearch/hyperbolics
4. An End-to-End Deep Learning Architecture for Graph Classiﬁcation
https://github.com/muhanzhang/DGCNN
https://github.com/muhanzhang/pytorch_DGCNN
5. Discriminative Embeddings of Latent Variable Models for Structured Data
https://github.com/Hanjun-Dai/pytorch_structure2vec
6. Decagon, Graph Neural Network for Multirelational Link Prediction
https://github.com/marinkaz/decagon
7. TF implementation for "LINE: Large-scale Information Network Embedding" 
https://github.com/snowkylin/line 
8. Keras implementation for "Structural Deep Network Embedding" [SDNE] 
https://github.com/xiaohan2012/sdne-keras
9. Learning to Make Predictions on Graphs with Autoencoders
https://github.com/vuptran/graph-representation-learning
10. Predicting multicellular function through multi-layer tissue networks 
https://github.com/marinkaz/ohmnet
11. VERSE, Versatile Graph Embeddings from Similarity Measures
https://github.com/xgfs/verse
12. C++ implementation of node2vec
https://github.com/xgfs/node2vec-c
13. C++ implementation of DeepWalk
https://github.com/xgfs/deepwalk-c

**Comment by chihming** [comment]
wow, thanks for the arrangement
Would you like to send me a commit (pull request), or I just add them by myself?

**Comment by ip01** [comment]
I'll make PR later today

**Comment by ip01** [comment]
#19
