### ISSUE TITLE
Additional paper

### ISSUE THREAD

**Issue by markheimann** [chihming/awesome-network-embedding#51]
Thanks for putting together this repository!  Here's another paper that might be relevant, since it also considers unsupervised network embedding in the context of the task of network alignment.  
Mark Heimann, Haoming Shen, Tara Safavi, and Danai Koutra. REGAL: Representation Learning-based Graph Alignment. International Conference on Information and Knowledge Management (CIKM), 2018. 

Paper: Arxiv preprint https://arxiv.org/pdf/1802.06257.pdf Official conference link [here](https://dl.acm.org/citation.cfm?id=3271788&dl=ACM&coll=DL)
Code: https://github.com/GemsLab/REGAL

**Comment by chihming** [comment]
will handle this later, thanks :)

**Comment by chihming** [comment]
updated.
