### ISSUE TITLE
Is there any directed, weighted and heterogeneous graph with node features?

### ISSUE THREAD

**Issue by Crystalsudo** [chihming/awesome-network-embedding#67]
Hi, thank you for your list of so many networks. 

Is there any directed, weighted and heterogeneous graph with node features? （node features are not text information, just continuous variable）

Look forward to your reply!

**Comment by chihming** [comment]
Would you like to try these [recommendation dataset](https://github.com/chihming/competitive-recsys#public-available-datasets)? and have a check on [SNAP dataset](http://snap.stanford.edu/data/index.html)

**Comment by Crystalsudo** [comment]
Thank you very much for your kind help!
